wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1664412595.213706
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 50
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.9.7
      5: 0.13.3
      6: 4.5.1
      8:
      - 3
      - 5
